apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::352365386023:role/eksctl-simple-jwt-nodegroup-ng-bb-NodeInstanceRole-G1QSA4RWCSQC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::352365386023:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-14T16:07:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1943"
  uid: 73be1995-824c-4286-a3fe-ced90629c6e6
