apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::431704086900:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CESV0C0N3QO0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::431704086900:role/EkeneKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-11T14:20:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1613"
  uid: a07748df-8d12-4bd5-8170-3320b211f39b
